"""Shared checker machinery for the Agentic AI course.

The tests import fakes and helpers from here so every module can be checked
OFFLINE - no Ollama, no Google, no Slack needed. Your task code must NEVER
import course_kit; it receives clients as parameters instead (dependency
injection). You may import it in a scratch script to experiment with the fakes.

DO NOT EDIT THIS FILE.
"""
import importlib
import importlib.util
import json
import sys
import urllib.request
from pathlib import Path
from types import SimpleNamespace

COURSE_ROOT = Path(__file__).resolve().parent


# --------------------------------------------------------------------------
# Loading student code
# --------------------------------------------------------------------------

def load_task(module_dir: str, filename: str):
    """Import a task file, e.g. load_task('0x00-environment_setup', '1-hello_qwen.py')."""
    import pytest
    path = COURSE_ROOT / module_dir / filename
    if not path.exists():
        pytest.fail(f"Missing file: {module_dir}/{filename} - create it, then re-run the checker.")
    mod_dir = str(path.parent)
    if mod_dir not in sys.path:            # lets task files do __import__('1-other_task')
        sys.path.insert(0, mod_dir)
    name = filename[:-3]
    spec = importlib.util.spec_from_file_location(name, path)
    mod = importlib.util.module_from_spec(spec)
    try:
        spec.loader.exec_module(mod)
    except Exception as exc:  # noqa: BLE001 - report any student-code crash
        pytest.fail(f"{module_dir}/{filename} crashed on import: {exc!r}")
    sys.modules[name] = mod
    return mod


def import_or_fail(module_name: str, hint: str):
    """Import a package module (core.agent, agents.gmail_agent, ...) with a friendly error."""
    import pytest
    try:
        return importlib.import_module(module_name)
    except Exception as exc:  # noqa: BLE001
        pytest.fail(f"Could not import '{module_name}': {exc!r}\nHint: {hint}")


def ollama_available() -> bool:
    try:
        urllib.request.urlopen("http://localhost:11434/api/tags", timeout=2)
        return True
    except Exception:  # noqa: BLE001
        return False


# --------------------------------------------------------------------------
# Fake LLM client (mimics the OpenAI SDK surface that Ollama exposes)
# --------------------------------------------------------------------------

class FakeToolCall:
    """Looks like an OpenAI SDK tool call: .id, .function.name, .function.arguments."""

    def __init__(self, name, arguments, call_id="call_1"):
        self.id = call_id
        self.type = "function"
        if not isinstance(arguments, str):
            arguments = json.dumps(arguments)
        self.function = SimpleNamespace(name=name, arguments=arguments)


class FakeMessage:
    def __init__(self, content=None, tool_calls=None):
        self.role = "assistant"
        self.content = content
        self.tool_calls = tool_calls


class FakeLLM:
    """Scriptable stand-in for openai.OpenAI().

    fake = FakeLLM(["hello", FakeMessage(tool_calls=[FakeToolCall("f", "{}")])])
    Each .chat.completions.create(...) call pops the next scripted response and
    records its kwargs in fake.calls.
    """

    def __init__(self, responses):
        self._responses = list(responses)
        self.calls = []
        self.embed_calls = []
        self.chat = SimpleNamespace(completions=SimpleNamespace(create=self._create))
        self.embeddings = SimpleNamespace(create=self._embed)

    def _embed(self, model=None, input=None, **kwargs):
        return _embed_response(self.embed_calls, model, input)

    def _create(self, **kwargs):
        recorded = dict(kwargs)
        if isinstance(kwargs.get("messages"), list):
            # snapshot: agents mutate their messages list after the call
            recorded["messages"] = list(kwargs["messages"])
        self.calls.append(recorded)
        if not self._responses:
            raise AssertionError(
                "FakeLLM ran out of scripted responses - your code called the "
                "model more times than this check expects."
            )
        resp = self._responses.pop(0)
        message = FakeMessage(content=resp) if isinstance(resp, str) else resp
        if kwargs.get("stream"):
            text = message.content or ""
            chunks = [
                SimpleNamespace(choices=[SimpleNamespace(
                    delta=SimpleNamespace(content=text[i:i + 4]), finish_reason=None)])
                for i in range(0, len(text), 4)
            ]
            chunks.append(SimpleNamespace(choices=[SimpleNamespace(
                delta=SimpleNamespace(content=None), finish_reason="stop")]))
            return iter(chunks)
        finish = "tool_calls" if message.tool_calls else "stop"
        return SimpleNamespace(choices=[SimpleNamespace(message=message, finish_reason=finish)])


# --------------------------------------------------------------------------
# Fake embeddings (deterministic bag-of-words, so "similar" really is similar)
# --------------------------------------------------------------------------

_VOCAB = ["python", "agent", "calendar", "email", "model", "tool", "meeting",
          "vector", "loop", "event"]


def _bow_vector(text):
    """A tiny deterministic 'embedding': how often each vocab term appears,
    plus a length feature so no vector is ever all zeros."""
    words = str(text).lower().split()
    vec = [float(sum(1 for w in words if term in w)) for term in _VOCAB]
    vec.append(len(words) / 100.0)
    return vec


def _embed_response(log, model, input):
    if isinstance(input, str):
        input = [input]
    input = list(input or [])
    log.append({"model": model, "input": input})
    data = [SimpleNamespace(embedding=_bow_vector(t), index=i)
            for i, t in enumerate(input)]
    return SimpleNamespace(data=data, model=model)


class FakeEmbedder:
    """Scriptless stand-in for a client used only for embeddings.

    fake = FakeEmbedder()
    fake.embeddings.create(model="m", input=["a", "b"]).data[0].embedding
    Every call is recorded in fake.calls.
    """

    def __init__(self):
        self.calls = []
        self.embeddings = SimpleNamespace(create=self._create)

    def _create(self, model=None, input=None, **kwargs):
        return _embed_response(self.calls, model, input)


def sample_documents():
    return [
        {"title": "agent-loop.md",
         "text": ("The agent loop sends the tool schemas to the model. The model "
                  "replies with tool calls and the agent runs each tool itself. "
                  "The agent then feeds every tool result back to the model, and "
                  "the loop repeats until the model answers with plain text.")},
        {"title": "calendar-notes.md",
         "text": ("Calendar events use RFC3339 timestamps. A timed meeting has a "
                  "start and an end with a dateTime, while an all-day event uses a "
                  "date instead. Always pass singleEvents when listing.")},
        {"title": "python-tips.md",
         "text": ("In python a function silently returns None when you forget the "
                  "return statement. Use isoformat to turn a datetime into a string, "
                  "and remember that sorted returns a new list.")},
    ]


# --------------------------------------------------------------------------
# Fake Google API services (mimic googleapiclient's chained-call style)
# --------------------------------------------------------------------------

class _Exec:
    def __init__(self, data):
        self._data = data

    def execute(self):
        return self._data


class FakeGmailService:
    """Supports: service.users().messages().list/get(...).execute()
                 service.users().drafts().create(...).execute()"""

    def __init__(self, messages=None):
        self.messages_store = messages or {}
        self.created_drafts = []
        self.last_list_kwargs = {}

    def users(self):
        return self

    def messages(self):
        return self

    def drafts(self):
        return self

    def list(self, userId="me", **kwargs):
        self.last_list_kwargs = kwargs
        ids = list(self.messages_store)
        n = kwargs.get("maxResults") or len(ids)
        return _Exec({"messages": [{"id": i} for i in ids[:n]],
                      "resultSizeEstimate": len(ids)})

    def get(self, userId="me", id=None, **kwargs):
        if id not in self.messages_store:
            raise KeyError(f"no such message id: {id}")
        data = dict(self.messages_store[id])
        data["id"] = id
        return _Exec(data)

    def create(self, userId="me", body=None, **kwargs):
        self.created_drafts.append(body)
        return _Exec({"id": f"draft_{len(self.created_drafts)}",
                      "message": {"id": f"m_draft_{len(self.created_drafts)}"}})


def sample_gmail_messages():
    return {
        "m1": {
            "snippet": "Can we meet tomorrow to discuss the budget?",
            "payload": {"headers": [
                {"name": "From", "value": "alice@example.com"},
                {"name": "Subject", "value": "Meeting request"},
                {"name": "Date", "value": "Mon, 13 Jul 2026 09:12:00 +0100"},
            ]},
        },
        "m2": {
            "snippet": "Please find the invoice attached.",
            "payload": {"headers": [
                {"name": "From", "value": "billing@corp.com"},
                {"name": "Subject", "value": "Invoice #42"},
                {"name": "Date", "value": "Sun, 12 Jul 2026 17:40:00 +0100"},
            ]},
        },
    }


class FakeCalendarService:
    """Supports: service.events().list/insert(...).execute()"""

    def __init__(self, events=None):
        self.events_store = events or []
        self.inserted = []
        self.last_list_kwargs = {}

    def events(self):
        return self

    def list(self, calendarId="primary", **kwargs):
        self.last_list_kwargs = kwargs
        n = kwargs.get("maxResults") or len(self.events_store)
        return _Exec({"items": self.events_store[:n]})

    def insert(self, calendarId="primary", body=None, **kwargs):
        self.inserted.append(body)
        return _Exec({"id": f"evt_{len(self.inserted)}",
                      "htmlLink": "https://calendar.google.com/event?eid=fake"})


def sample_calendar_events():
    return [
        {"id": "e1", "summary": "Standup",
         "start": {"dateTime": "2026-07-14T09:00:00+01:00"},
         "end": {"dateTime": "2026-07-14T09:15:00+01:00"}},
        {"id": "e2", "summary": "Focus block",
         "start": {"dateTime": "2026-07-14T11:00:00+01:00"},
         "end": {"dateTime": "2026-07-14T12:30:00+01:00"}},
        {"id": "e3", "summary": "Team offsite",
         "start": {"date": "2026-07-15"},
         "end": {"date": "2026-07-16"}},
    ]


# --------------------------------------------------------------------------
# Fake Slack client (mimics slack_sdk.WebClient)
# --------------------------------------------------------------------------

class FakeSlackClient:
    def __init__(self, history=None):
        # newest-first, exactly like the real conversations.history API
        self.history = history or []
        self.posted = []

    def chat_postMessage(self, channel=None, text=None, **kwargs):
        self.posted.append({"channel": channel, "text": text})
        return {"ok": True, "channel": channel,
                "ts": f"171000000{len(self.posted)}.000100"}

    def conversations_history(self, channel=None, limit=10, **kwargs):
        return {"ok": True, "messages": self.history[:limit]}


def sample_slack_history():
    return [
        {"user": "U333", "text": "third (newest)", "ts": "1710000003.000100"},
        {"user": "U222", "text": "second", "ts": "1710000002.000100"},
        {"user": "U111", "text": "first (oldest)", "ts": "1710000001.000100"},
    ]
